export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/usr/local/opt/fzf/bin

export ZSH=$HOME/.oh-my-zsh

ZSH_THEME="alexn-local"

ENABLE_CORRECTION="true"

COMPLETION_WAITING_DOTS="true"

plugins=(git golang go)

source $ZSH/oh-my-zsh.sh
# . `brew --prefix`/etc/profile.d/z.sh

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
