Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  # config.vm.synced_folder "/Users/alexn-macbook/Workspace", "/home/vagrant/workspace"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y git
    git clone git://github.com/bk-ez/dotfiles /home/vagrant/dotfiles
 #  sudo /home/vagrant/dotfiles/setup-env.sh
  SHELL
end
